server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/testDB
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    jackson:
      time-zone: Asia/Seoul

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging:
  level:
    org.hibernate.type: trace

security:
  key: "d1b92e60-8745-4e0c-a97c-127d4c8575ed"
  salt: "70726574657374"

jwt:
  key: "123456456asgdjkasghjk3asdkalsdagsdjabdskagsdilajgdilagi12g32i13123123123kadgjfajyafdhy"