package com.example.todolist.global.exception;

public enum ErrorCode {

    ERROR_INVALID_TOKEN_SIGNATURE("ERROR_INVALID_TOKEN_SIGNATURE"),
    ERROR_EXPIRED_TOKEN("ERROR_EXPIRED_TOKEN"),
    ERROR_UNSUPPORTED_TOKEN("ERROR_UNSUPPORTED_TOKEN"),
    ERROR_UNAUTHORIZED("ERROR_UNAUTHORIZED"),
    ERROR_FORBIDDEN("ERROR_FORBIDDEN"),

    ERROR_AVAILABLE_MEMBER_NOT_FOUND("ERROR_AVAILABLE_MEMBER_NOT_FOUND"),
    ERROR_ALREADY_REGISTERED_MEMBER_ID("ERROR_ALREADY_REGISTERED_MEMBER_ID"),
    ERROR_ALREADY_REGISTERED_MEMBER_NICKNAME("ERROR_ALREADY_REGISTERED_MEMBER_NICKNAME"),
    ERROR_ALREADY_REGISTERED_USER("ERROR_ALREADY_REGISTERED_USER"),
    ERROR_USER_ID_INCORRECT_FORMAT("ERROR_USER_ID_INCORRECT_FORMAT"),
    ERROR_USER_NAME_INCORRECT_FORMAT("ERROR_USER_NAME_INCORRECT_FORMAT"),
    ERROR_USER_REG_NO_INCORRECT_FORMAT("ERROR_USER_REG_NO_INCORRECT_FORMAT"),
    ERROR_USER_PASSWORD_INCORRECT_FORMAT("ERROR_USER_PASSWORD_INCORRECT_FORMAT"),

    ;

    private final String errorCode;

    ErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    public String getErrorCode() {
        return errorCode;
    }
}
